### PR TITLE
backend: add a route /list

### LINKED ISSUE #6: Add a router to get list
Add a route `/list/` to get a list from the DB.

### PR DESCRIPTION
**Pull request by katilp**
Closes #6

### CODE REVIEW

**Comment by katilp** [comment]
The latest pushes make it work
- removed unnecessary intermediate function
- made get function async
- stringified the result
- removed the db access code from app.js

Route /list gives now the json list

**Comment by katilp** [comment]
Commit 115927c3011432a6a618a345352831108f58002f 
- changes `res.render` to `res.send` 
- adds an optional query parameter

  `http://<IP>/list` returns the full list
  `http://<IP>/list/?item_id=<N>` returns the item with item_id N

**Comment by katilp** [comment]
Commit e9388c8cc49b75287bb6e3ee1e93286c1dba39a7 makes proper use of `req.params`
The single element call is now without a query

  `http://<IP>/list` returns the full list
  `http://<IP>/list/item_id/<N>` returns the item with item_id N

**Comment by katilp** [comment]
Commit e7abf3b84c92971480c46e3fa93901c599da473d modifies the return value for a single item query to be an object and not an array.
The full list is an array of objects.

**Review by elisakaisa — APPROVED** [review]
LGTM

**Pull request merged**
